site_name: Profile
nav:
  - About: index.md
  - Education: education.md
  - Experience: experience.md
  - 'Skills':
    - 'Technical Writing': 'skill-1.md'
    - 'Written and Spoken English': 'skill-2.md'
    - 'Adobe Creative Suite': 'skill-3.md'
  - Selected Past Work: past-work.md
  - Test of New File: MDexercise.md

theme:
  name: material
  logo: images/wizeline_isotype.png

extra_css:
  - css/style.css